from typing import Any

session: Any
local: Any
Redirect: Any

def _(msg: str) -> str: ...
def throw(msg: str, title: str | None = None) -> None: ...
def get_app_path(*path: str) -> str: ...
def __getattr__(name: str) -> Any: ...
